name: Docker Images

on:
  push:
    branches:
      - '**'
    tags:
      - "v*"
    paths:
      - .github/workflows/docker.yml
      - "docker-bake.hcl"
      - "Dockerfile"

jobs:

  Docker-Bake:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        target: ['alpine', 'distroless']
    steps:

    - name: Login to Docker
      uses: docker/login-action@v2
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login To GitHub
      uses: docker/login-action@v2
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v3.8.0
      with:
        images: cyb3rjak3/udpt,ghcr.io/cyb3r-jak3/udpt
        tags: |
          type=sha
        labels: |
          org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/docker-udpt.git
          org.label-schema.schema-version=1.0.0-rc1
          maintainer=Cyb3r Jak3 jake@jwhite.network
          org.opencontainers.image.vendor=cyb3rjak3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.7.0
      with:
        buildkitd-flags: --debug

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      uses: docker/bake-action@v1.7.0
      with:
        files: |
          ./docker-bake.hcl
          ${{ steps.meta.outputs.bake-file }}
        set: |
          *.cache-to=type=gha,mode=max
          *.cache-from=type=gha
        targets: ${{ matrix.target }}-release
        push: ${{ startsWith(github.ref, 'refs/tags/v') }}
